"""Obsidian vault scanner — the read-only "second brain" corpus.

Reads the Obsidian vault registry (`%APPDATA%/obsidian/obsidian.json`) and the
vaults on disk. Every vault here is generated by the user's `graphify` skill as a
code knowledge graph of a project: ~one markdown note per code symbol plus a
precomputed `graph.json` / `GRAPH_REPORT.md` in the parent `graphify-out/` dir.

The vault path encodes its project root (strip the trailing `/graphify-out/<dir>`),
which matches `Session.project_path` of CLI sessions already tracked by INDRA — so a
vault and its agent sessions/traces unify under one project.

Strictly read-only: only reads `.md` / `.json` files. Never writes. Safe to run
while a vault is open in Obsidian (plain text/JSON reads take no lock; partial
mid-save reads are tolerated via errors="replace" + try/except).

Pattern mirrors `aditya/pushanah/claude_env.py` (plain dicts, `_helpers`, silent
error handling).
"""

from __future__ import annotations

import json
import logging
import os
import re
from datetime import UTC, datetime
from pathlib import Path

log = logging.getLogger(__name__)

# Cap a single note body so a pathological file can't blow up a response.
_MAX_NOTE_BYTES = 256 * 1024
# Hard ceiling on notes returned in one page.
_MAX_NOTES_PAGE = 500
# Cap nodes returned by read_graph — a force-directed view can't render (and the
# browser can't hold) tens of thousands of nodes. Larger graphs are truncated.
_MAX_GRAPH_NODES = 3000
_GRAPHIFY_MARKER = "/graphify-out/"

# Combined "second brain" graph: per-vault cluster colors, the global node cap,
# and the size above which a vault contributes only a hub node (so we never parse
# a giant graph.json on a hero request).
_VAULT_PALETTE = [
    "#6dd5e8", "#e0b050", "#7c6af7", "#2ab870", "#e0708a", "#d4843a",
    "#4dc8c8", "#a855f7", "#9acd4d", "#5a9ccf", "#c98ae0", "#48b3a0",
]
_COMBINED_DEFAULT_CAP = 800
_COMBINED_INNER_MAX = 2500


# ── registry + path helpers ──────────────────────────────────────────────────


def _obsidian_json_path() -> Path:
    appdata = os.environ.get("APPDATA")
    base = Path(appdata) if appdata else Path.home() / "AppData" / "Roaming"
    return base / "obsidian" / "obsidian.json"


def _load_registry() -> dict[str, dict]:
    """Return {vault_id: {"path": str, "ts": int, "open": bool}} or {}."""
    path = _obsidian_json_path()
    try:
        data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except (OSError, ValueError):
        return {}
    vaults = data.get("vaults") if isinstance(data, dict) else None
    return vaults if isinstance(vaults, dict) else {}


def _norm(p: str | None) -> str:
    """Case-insensitive, slash-normalized path for cross-OS comparison."""
    if not p:
        return ""
    return p.replace("\\", "/").rstrip("/").lower()


def _project_root(vault_path: str) -> str | None:
    """Strip a trailing `/graphify-out/<vaultdir>` to recover the project root.

    Returns the original-cased root with forward slashes, or None if the vault
    isn't a graphify-style vault.
    """
    norm = vault_path.replace("\\", "/").rstrip("/")
    idx = norm.lower().rfind(_GRAPHIFY_MARKER)
    if idx == -1:
        return None
    return norm[:idx] or None


def _vault_dir(vault_id: str) -> Path | None:
    entry = _load_registry().get(vault_id)
    if not isinstance(entry, dict):
        return None
    raw = entry.get("path")
    return Path(raw) if isinstance(raw, str) and raw else None


def _iso_from_ms(ms: int | str | float | None) -> str | None:
    if ms is None:
        return None
    try:
        return datetime.fromtimestamp(int(ms) / 1000, tz=UTC).isoformat()
    except (TypeError, ValueError, OverflowError, OSError):
        return None


def _iso_mtime(path: Path) -> str | None:
    try:
        return datetime.fromtimestamp(path.stat().st_mtime, tz=UTC).isoformat()
    except OSError:
        return None


# ── graphify artifacts (graph.json / GRAPH_REPORT.md) ────────────────────────


def _artifacts_dir(vault_dir: Path) -> Path:
    """The `graphify-out/` dir (parent of the vault) holding graph.json etc."""
    return vault_dir.parent


_REPORT_RE = re.compile(
    r"(\d+)\s*nodes?.*?(\d+)\s*edges?.*?(\d+)\s*communit", re.IGNORECASE | re.DOTALL
)


def _graph_counts(artifacts: Path) -> dict | None:
    """Cheap node/edge/community counts from GRAPH_REPORT.md, else graph.json."""
    report = artifacts / "GRAPH_REPORT.md"
    try:
        if report.exists():
            m = _REPORT_RE.search(report.read_text(encoding="utf-8", errors="replace"))
            if m:
                return {
                    "node_count": int(m.group(1)),
                    "edge_count": int(m.group(2)),
                    "community_count": int(m.group(3)),
                }
    except (OSError, ValueError):
        pass
    graph = _load_graph_json(artifacts)
    if graph is None:
        return None
    nodes = graph.get("nodes") or []
    links = graph.get("links") or graph.get("edges") or []
    communities = {n.get("community") for n in nodes if isinstance(n, dict)}
    communities.discard(None)
    return {
        "node_count": len(nodes),
        "edge_count": len(links),
        "community_count": len(communities),
    }


def _load_graph_json(artifacts: Path) -> dict | None:
    gj = artifacts / "graph.json"
    try:
        if not gj.exists():
            return None
        data = json.loads(gj.read_text(encoding="utf-8", errors="replace"))
        return data if isinstance(data, dict) else None
    except (OSError, ValueError):
        return None


# ── note helpers ─────────────────────────────────────────────────────────────


def _count_notes(vault_dir: Path) -> int:
    try:
        return sum(1 for _ in vault_dir.glob("*.md"))
    except OSError:
        return 0


def _safe_note_path(vault_dir: Path, name: str) -> Path | None:
    """Resolve `name` to a note inside `vault_dir`, or None if unsafe/missing.

    Guards against path traversal: the name must be a bare filename (no
    separators, no `..`) and the resolved path must sit directly inside the
    vault dir.
    """
    if not name or name in (".", ".."):
        return None
    # Reject any path separators, parent refs, or NTFS stream markers (`:`) —
    # notes are flat plain-`.md` files in the vault. A bare `:` would otherwise
    # let `note.md:stream` reach an alternate data stream.
    if "/" in name or "\\" in name or ":" in name or os.path.basename(name) != name:
        return None
    if not name.endswith(".md"):
        name = f"{name}.md"
    try:
        vault_real = vault_dir.resolve(strict=True)
        candidate = (vault_dir / name).resolve(strict=False)
    except OSError:
        return None
    # Must be a direct child of the vault dir and actually exist as a file.
    if candidate.parent != vault_real or not candidate.is_file():
        return None
    return candidate


# ── public API (used by router AND naksatrani rebuild_graph) ─────────────────


def _summarize(vault_id: str, entry: dict) -> dict:
    raw_path = entry.get("path") if isinstance(entry, dict) else None
    path = raw_path if isinstance(raw_path, str) else ""
    vault_dir = Path(path) if path else None
    exists = bool(vault_dir and vault_dir.exists())
    project_root = _project_root(path) if path else None
    artifacts = _artifacts_dir(vault_dir) if vault_dir else None

    counts = _graph_counts(artifacts) if (exists and artifacts) else None
    note_count = _count_notes(vault_dir) if exists and vault_dir else 0

    return {
        "id": vault_id,
        "name": vault_dir.name if vault_dir else vault_id,
        "path": path,
        "exists": exists,
        "open": bool(entry.get("open")) if isinstance(entry, dict) else False,
        "is_graphify": project_root is not None,
        "project_root": project_root,
        "note_count": note_count,
        "graph": counts,
        "last_modified": _iso_mtime(vault_dir) if exists and vault_dir else _iso_from_ms(
            entry.get("ts") if isinstance(entry, dict) else None
        ),
    }


def scan_vaults() -> list[dict]:
    """One summary dict per registered vault, newest-touched first."""
    out = [_summarize(vid, entry) for vid, entry in _load_registry().items()]
    out.sort(key=lambda v: v.get("last_modified") or "", reverse=True)
    return out


def get_vault(vault_id: str) -> dict | None:
    entry = _load_registry().get(vault_id)
    if not isinstance(entry, dict):
        return None
    return _summarize(vault_id, entry)


def list_notes(vault_id: str, limit: int = 100, offset: int = 0) -> dict | None:
    vault_dir = _vault_dir(vault_id)
    if vault_dir is None or not vault_dir.exists():
        return None
    limit = max(1, min(limit, _MAX_NOTES_PAGE))
    offset = max(0, offset)
    try:
        files = sorted(vault_dir.glob("*.md"), key=lambda p: p.name.lower())
    except OSError:
        files = []
    total = len(files)
    notes: list[dict] = []
    for f in files[offset : offset + limit]:
        try:
            st = f.stat()
            notes.append(
                {
                    "name": f.name,
                    "stem": f.stem,
                    "size": st.st_size,
                    "modified_at": _iso_mtime(f),
                }
            )
        except OSError:
            continue
    return {
        "vault_id": vault_id,
        "total": total,
        "limit": limit,
        "offset": offset,
        "notes": notes,
    }


def read_note(vault_id: str, name: str, max_bytes: int = _MAX_NOTE_BYTES) -> dict | None:
    vault_dir = _vault_dir(vault_id)
    if vault_dir is None:
        return None
    note = _safe_note_path(vault_dir, name)
    if note is None:
        return None
    try:
        st = note.stat()
        # Read only a bounded prefix (+1 byte to detect truncation) so a
        # pathologically large file can't exhaust memory before the cap applies.
        with note.open("rb") as fh:
            raw = fh.read(max_bytes + 1)
    except OSError:
        return None
    truncated = len(raw) > max_bytes
    body = raw[:max_bytes].decode("utf-8", errors="replace")
    return {
        "vault_id": vault_id,
        "name": note.name,
        "stem": note.stem,
        "size": st.st_size,
        "modified_at": _iso_mtime(note),
        "truncated": truncated,
        "body": body,
    }


def read_graph(vault_id: str) -> dict | None:
    """Normalize the precomputed graphify graph.json into the frontend
    ConstellationGraph shape: {nodes, edges, node_count, edge_count, ...}."""
    vault_dir = _vault_dir(vault_id)
    if vault_dir is None or not vault_dir.exists():
        return None
    artifacts = _artifacts_dir(vault_dir)
    graph = _load_graph_json(artifacts)
    if graph is None:
        return {
            "vault_id": vault_id,
            "is_graphify": False,
            "nodes": [],
            "edges": [],
            "node_count": 0,
            "edge_count": 0,
            "community_count": 0,
        }

    raw_nodes = graph.get("nodes") or []
    raw_links = graph.get("links") or graph.get("edges") or []
    total_nodes = len(raw_nodes)
    total_edges = len(raw_links)
    truncated = total_nodes > _MAX_GRAPH_NODES
    if truncated:
        raw_nodes = raw_nodes[:_MAX_GRAPH_NODES]

    id_map: dict[object, str] = {}
    nodes: list[dict] = []
    communities: set[object] = set()
    for i, n in enumerate(raw_nodes):
        if not isinstance(n, dict):
            continue
        nid = f"n{i}"
        orig = n.get("id", i)
        id_map[orig] = nid
        community = n.get("community")
        communities.add(community)
        nodes.append(
            {
                "id": nid,
                "entity_type": "symbol",
                "entity_id": str(orig),
                "label": n.get("label") or n.get("norm_label") or str(orig),
                "domain": "smriti",
                "properties": {
                    "community": community,
                    "file_type": n.get("file_type"),
                    "source_file": n.get("source_file"),
                },
            }
        )

    edges: list[dict] = []
    for j, e in enumerate(raw_links):
        if not isinstance(e, dict):
            continue
        src = e.get("_src", e.get("source"))
        tgt = e.get("_tgt", e.get("target"))
        fn = id_map.get(src)
        tn = id_map.get(tgt)
        if fn is None or tn is None:
            continue
        try:
            weight = float(e.get("weight") or 1.0)
        except (TypeError, ValueError):
            weight = 1.0
        edges.append(
            {
                "id": f"e{j}",
                "from_node_id": fn,
                "to_node_id": tn,
                "relationship": e.get("relation") or "related",
                "weight": weight,
                "properties": {"confidence": e.get("confidence")},
            }
        )

    communities.discard(None)
    return {
        "vault_id": vault_id,
        "is_graphify": True,
        "nodes": nodes,
        "edges": edges,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "community_count": len(communities),
        "truncated": truncated,
        "total_node_count": total_nodes,
        "total_edge_count": total_edges,
    }


def _link_ends(e: dict) -> tuple[object, object]:
    return e.get("_src", e.get("source")), e.get("_tgt", e.get("target"))


def _nsid(vault_id: str, oid: object) -> str:
    """Namespace a vault-local node id into the combined graph."""
    return f"{vault_id}:{oid}"


def combined_graph(cap: int = _COMBINED_DEFAULT_CAP) -> dict:
    """One Obsidian-style force graph of every vault at once.

    Each existing graphify vault becomes a colored cluster: a vault hub node plus
    its highest-degree symbol nodes (a per-vault slice of the global `cap`) with
    their intra-vault edges, anchored to the hub and to a shared project node.
    Vaults larger than `_COMBINED_INNER_MAX` contribute only a hub (we never parse
    their giant graph.json here). Symbol nodes carry `properties.color` so the
    frontend renders each vault as its own cluster colour.
    """
    summaries = [v for v in scan_vaults() if v.get("exists") and v.get("is_graphify")]
    expandable = [
        v for v in summaries
        if (v.get("graph") or {}).get("node_count", 0) <= _COMBINED_INNER_MAX
    ]
    budget = max(25, cap // max(len(expandable), 1)) if expandable else 0

    nodes: list[dict] = []
    edges: list[dict] = []
    proj_ids: dict[str, str] = {}

    def project_node(root: str) -> str:
        key = _norm(root)
        if key not in proj_ids:
            nid = f"project:{key}"
            proj_ids[key] = nid
            leaf = root.replace("\\", "/").rstrip("/").split("/")[-1] or root
            nodes.append({
                "id": nid, "entity_type": "project", "entity_id": root,
                "label": leaf, "domain": "smriti", "properties": {"path": root},
            })
        return proj_ids[key]

    for i, v in enumerate(summaries):
        vid = v["id"]
        color = _VAULT_PALETTE[i % len(_VAULT_PALETTE)]
        hub_id = f"vault:{vid}"
        nodes.append({
            "id": hub_id, "entity_type": "vault", "entity_id": vid,
            "label": v["name"], "domain": "smriti",
            "properties": {"color": color, "note_count": v.get("note_count", 0)},
        })
        root = v.get("project_root")
        if root:
            pid = project_node(root)
            edges.append({
                "id": f"e:{hub_id}->{pid}", "from_node_id": hub_id, "to_node_id": pid,
                "relationship": "documents", "weight": 1.0, "properties": {},
            })

        if (v.get("graph") or {}).get("node_count", 0) > _COMBINED_INNER_MAX:
            continue  # huge vault — hub only
        vault_dir = _vault_dir(vid)
        graph = _load_graph_json(_artifacts_dir(vault_dir)) if vault_dir else None
        if graph is None:
            continue
        raw_nodes = [n for n in (graph.get("nodes") or []) if isinstance(n, dict)]
        raw_links = [e for e in (graph.get("links") or graph.get("edges") or []) if isinstance(e, dict)]

        deg: dict[object, int] = {}
        for e in raw_links:
            s, t = _link_ends(e)
            deg[s] = deg.get(s, 0) + 1
            deg[t] = deg.get(t, 0) + 1

        ranked = sorted(raw_nodes, key=lambda n: deg.get(n.get("id"), 0), reverse=True)
        kept = ranked[:budget]
        kept_ids = {n.get("id") for n in kept}

        anchor: str | None = None
        for k, n in enumerate(kept):
            sid = _nsid(vid, n.get("id"))
            if k == 0:
                anchor = sid
            nodes.append({
                "id": sid, "entity_type": "symbol", "entity_id": str(n.get("id")),
                "label": n.get("label") or n.get("norm_label") or str(n.get("id")),
                "domain": "smriti",
                "properties": {
                    "color": color, "vault": v["name"],
                    "community": n.get("community"), "file_type": n.get("file_type"),
                },
            })
        if anchor:
            edges.append({
                "id": f"e:{hub_id}=>{anchor}", "from_node_id": hub_id, "to_node_id": anchor,
                "relationship": "documents", "weight": 1.0, "properties": {},
            })
        for j, e in enumerate(raw_links):
            s, t = _link_ends(e)
            if s in kept_ids and t in kept_ids:
                edges.append({
                    "id": f"e:{vid}:{j}", "from_node_id": _nsid(vid, s), "to_node_id": _nsid(vid, t),
                    "relationship": e.get("relation") or "related", "weight": 1.0,
                    "properties": {},
                })

    return {
        "nodes": nodes,
        "edges": edges,
        "node_count": len(nodes),
        "edge_count": len(edges),
        "vault_count": len(summaries),
        "expanded": len(expandable),
    }
